<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageId>Xs.Cli.Main</PackageId>
        <PackageVersion>0.1.0</PackageVersion>
        <Description>XS cli main project. Entrypoint, contains all commands and tasks. Uses registry client and type-related projects for work.</Description>
        <TargetFramework>netcoreapp2.2</TargetFramework>
        <OutputType>Exe</OutputType>
        <DebugType>portable</DebugType>
        <LangVersion>latest</LangVersion>
        <WarningsAsErrors>true</WarningsAsErrors>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../Xs.Cli.Dotnet/Xs.Cli.Dotnet.csproj" />
        <ProjectReference Include="../Xs.Cli.Node/Xs.Cli.Node.csproj" />
        <ProjectReference Include="../../../registry/client/src/Xs.RegistryClient.Main/Xs.RegistryClient.Main.csproj" />
        <ProjectReference Include="../../../registry/client/src/Xs.RegistryClient.Server/Xs.RegistryClient.Server.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Annium.Core.Entrypoint" Version="0.1.0" />
        <PackageReference Include="Annium.Extensions.CommandLine" Version="0.1.0" />
    </ItemGroup>
</Project>