<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netcoreapp2.2</TargetFramework>
        <DebugType>Portable</DebugType>
        <OutputType>Exe</OutputType>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../Xs.Cli.Dotnet/Xs.Cli.Dotnet.csproj" />
        <ProjectReference Include="../Xs.Cli.Node/Xs.Cli.Node.csproj" />
        <ProjectReference Include="../../../registry/client/src/Xs.RegistryClient.Dotnet/Xs.RegistryClient.Dotnet.csproj" />
        <ProjectReference Include="../../../registry/client/src/Xs.RegistryClient.Node/Xs.RegistryClient.Node.csproj" />
        <ProjectReference Include="../../../registry/client/src/Xs.RegistryClient.Main/Xs.RegistryClient.Main.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Annium.Extensions.Arguments" Version="0.1.0" />
        <PackageReference Include="Annium.Extensions.Entrypoint" Version="0.1.0" />
    </ItemGroup>
</Project>