<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageId>Xs.Execution</PackageId>
        <PackageVersion>0.1.0</PackageVersion>
        <TargetFramework>netcoreapp2.2</TargetFramework>
        <OutputType>Library</OutputType>
        <DebugType>Portable</DebugType>
    </PropertyGroup>
</Project>