<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageId>Xs.RegistryClient.Main</PackageId>
        <PackageVersion>0.1.0</PackageVersion>
        <Description>XS registry client for main server.</Description>
        <TargetFramework>net6.0</TargetFramework>
        <OutputType>Library</OutputType>
        <DebugType>portable</DebugType>
        <LangVersion>10.0</LangVersion>
        <WarningsAsErrors>true</WarningsAsErrors>
        <IsPackable>false</IsPackable>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../Xs.RegistryClient.Shared/Xs.RegistryClient.Shared.csproj" />
    </ItemGroup>
</Project>