<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Solutions>Xx</Solutions>
        <OutputType>Exe</OutputType>
        <IsPackable>true</IsPackable>
        <PackAsTool>true</PackAsTool>
        <ToolCommandName>xx</ToolCommandName>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../../../server/src/Server.Client/Server.Client.csproj" />
        <ProjectReference Include="../Xx.Cli.Dotnet/Xx.Cli.Dotnet.csproj" />
        <ProjectReference Include="../Xx.Cli.Node/Xx.Cli.Node.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Annium.Core.Entrypoint" />
        <PackageReference Include="Annium.Net.Servers.Web" />
        <PackageReference Include="LibGit2Sharp" />
        <PackageReference Include="QuikGraph.Graphviz" />
    </ItemGroup>
</Project>