include /etc/nginx/conf.d/parts/http.conf;

server {
    include /etc/nginx/conf.d/parts/server.conf;

    listen 9901;

    set $upstream 192.168.99.1:5000;

    location / {
        include /etc/nginx/conf.d/parts/location_proxy.conf;

        rewrite /(.*) /main/$1 break;
        proxy_pass http://$upstream/main/$1$is_args$args;
    }
}

server {
    include /etc/nginx/conf.d/parts/server.conf;

    listen 9902;

    set $upstream 192.168.99.1:5000;

    location / {
        include /etc/nginx/conf.d/parts/location_proxy.conf;

        rewrite /(.*) /dotnet/$1 break;
        proxy_pass http://$upstream/dotnet/$1$is_args$args;
    }
}

server {
    include /etc/nginx/conf.d/parts/server.conf;

    listen 9903;

    set $upstream 192.168.99.1:5000;

    location / {
        include /etc/nginx/conf.d/parts/location_proxy.conf;

        rewrite /(.*) /node/$1 break;
        proxy_pass http://$upstream/node/$1$is_args$args;
    }
}