server {
    include /etc/nginx/conf.d/parts/server.conf;

    listen 443 ssl http2;
    server_name registry.annium.com;

    ssl_certificate /etc/certs/registry.annium.com/cert.crt;
    ssl_certificate_key /etc/certs/registry.annium.com/cert.key;
    ssl_trusted_certificate /etc/certs/registry.annium.com/cert.crt;

    set $upstream_server registry-server:5000;
    set $upstream_ui registry-ui:3000;

    # Portus needs to handle /v2/token for authentication
    location = /v2/token {
        include /etc/nginx/conf.d/parts/location_proxy.conf;

        rewrite /(.*) /$1 break;
        proxy_pass https://$upstream_ui/$1$is_args$args;
    }

    # Portus needs to handle /v2/webhooks/events for notifications
    location = /v2/webhooks/events {
        include /etc/nginx/conf.d/parts/location_proxy.conf;

        rewrite /(.*) /$1 break;
        proxy_pass https://$upstream_ui/$1$is_args$args;
    }

    location /v2/ {
        include /etc/nginx/conf.d/parts/location_proxy.conf;

        # Do not allow connections from docker 1.5 and earlier
        # docker pre-1.6.0 did not properly set the user agent on ping, catch "Go *" user agents
        if ($http_user_agent ~ "^(docker\/1\.(3|4|5(?!\.[0-9]-dev))|Go ).*$" ) {
            return 404;
        }

        ## If $docker_distribution_api_version is empty, the header will not be added.
        ## See the map directive above where this variable is defined.
        add_header 'Docker-Distribution-Api-Version'
            $docker_distribution_api_version
            always;

        rewrite /(.*) /$1 break;
        proxy_pass https://$upstream_server/$1$is_args$args;
    }

    location / {
        try_files $uri/index.html $uri.html $uri @portus;
    }

    location @portus {
        include /etc/nginx/conf.d/parts/location_proxy.conf;

        rewrite /(.*) /$1 break;
        proxy_pass https://$upstream_ui/$1$is_args$args;
    }
}