// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Xs.Registry.Db;

namespace Xs.Registry.Db.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Xs.Registry.Db.Dotnet.Entities.Package", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<int>("Downloads");

                    b.Property<string>("LowerName")
                        .IsRequired();

                    b.Property<Guid>("MetaPackageId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<DateTime>("Published");

                    b.Property<string>("Version")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasAlternateKey("LowerName", "Version");

                    b.HasIndex("MetaPackageId");

                    b.ToTable("DotnetPackages");
                });

            modelBuilder.Entity("Xs.Registry.Db.Dotnet.Entities.PackageDependency", b =>
                {
                    b.Property<Guid>("PackageId");

                    b.Property<string>("Framework");

                    b.Property<string>("Name");

                    b.Property<string>("Version")
                        .IsRequired();

                    b.HasKey("PackageId", "Framework", "Name");

                    b.ToTable("DotnetPackageDependencies");
                });

            modelBuilder.Entity("Xs.Registry.Db.Node.Entities.Package", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<int>("Downloads");

                    b.Property<string>("Integrity")
                        .IsRequired();

                    b.Property<string>("LowerName")
                        .IsRequired();

                    b.Property<string>("Main")
                        .IsRequired();

                    b.Property<Guid>("MetaPackageId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<DateTime>("Published");

                    b.Property<string>("Shasum")
                        .IsRequired();

                    b.Property<string>("Version")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasAlternateKey("LowerName", "Version");

                    b.HasIndex("MetaPackageId");

                    b.ToTable("NodePackages");
                });

            modelBuilder.Entity("Xs.Registry.Db.Node.Entities.PackageDependency", b =>
                {
                    b.Property<Guid>("PackageId");

                    b.Property<string>("Name");

                    b.Property<int>("Type");

                    b.Property<string>("Version")
                        .IsRequired();

                    b.HasKey("PackageId", "Name");

                    b.ToTable("NodePackageDependencies");
                });

            modelBuilder.Entity("Xs.Registry.Db.Shared.Entities.MetaPackage", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<int>("Downloads");

                    b.Property<string>("LowerName")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<Guid>("OwnerId");

                    b.Property<DateTime>("Published");

                    b.Property<string>("Type")
                        .IsRequired();

                    b.Property<string>("Version")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasAlternateKey("Type", "LowerName");

                    b.HasIndex("OwnerId");

                    b.ToTable("MetaPackages");
                });

            modelBuilder.Entity("Xs.Registry.Db.Shared.Entities.MetaPackagePermission", b =>
                {
                    b.Property<Guid>("MetaPackageId");

                    b.Property<int>("Category");

                    b.Property<int>("Permission");

                    b.HasKey("MetaPackageId", "Category");

                    b.ToTable("MetaPackagePermissions");
                });

            modelBuilder.Entity("Xs.Registry.Db.Shared.Entities.User", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<Guid>("ApiToken");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("PasswordHash")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Xs.Registry.Db.Shared.Entities.UserSession", b =>
                {
                    b.Property<Guid>("Token");

                    b.Property<DateTime>("Expires");

                    b.Property<Guid>("UserId");

                    b.HasKey("Token");

                    b.HasIndex("UserId");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("Xs.Registry.Db.Dotnet.Entities.Package", b =>
                {
                    b.HasOne("Xs.Registry.Db.Shared.Entities.MetaPackage")
                        .WithMany()
                        .HasForeignKey("MetaPackageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Xs.Registry.Db.Dotnet.Entities.PackageDependency", b =>
                {
                    b.HasOne("Xs.Registry.Db.Dotnet.Entities.Package")
                        .WithMany("Dependencies")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Xs.Registry.Db.Node.Entities.Package", b =>
                {
                    b.HasOne("Xs.Registry.Db.Shared.Entities.MetaPackage")
                        .WithMany()
                        .HasForeignKey("MetaPackageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Xs.Registry.Db.Node.Entities.PackageDependency", b =>
                {
                    b.HasOne("Xs.Registry.Db.Node.Entities.Package")
                        .WithMany("Dependencies")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Xs.Registry.Db.Shared.Entities.MetaPackage", b =>
                {
                    b.HasOne("Xs.Registry.Db.Shared.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Xs.Registry.Db.Shared.Entities.MetaPackagePermission", b =>
                {
                    b.HasOne("Xs.Registry.Db.Shared.Entities.MetaPackage")
                        .WithMany("Permissions")
                        .HasForeignKey("MetaPackageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Xs.Registry.Db.Shared.Entities.UserSession", b =>
                {
                    b.HasOne("Xs.Registry.Db.Shared.Entities.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
