<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Annium.AspNetCore.Extensions" Version="1.1.35" />
    <PackageVersion Include="Annium.Configuration.CommandLine" Version="1.1.47" />
    <PackageVersion Include="Annium.Configuration.Yaml" Version="1.1.47" />
    <PackageVersion Include="Annium.Core.Entrypoint" Version="1.1.47" />
    <PackageVersion Include="Annium.Data.Operations.Serialization.Json" Version="1.1.47" />
    <PackageVersion Include="Annium.DbUp.PostgreSql" Version="1.1.35" />
    <PackageVersion Include="Annium.Execution.Flow" Version="1.1.47" />
    <PackageVersion Include="Annium.Extensions.Arguments" Version="1.1.47" />
    <PackageVersion Include="Annium.Extensions.CommandLine" Version="1.1.47" />
    <PackageVersion Include="Annium.Extensions.Shell" Version="1.1.47" />
    <PackageVersion Include="Annium.Infrastructure.Hosting" Version="1.1.35" />
    <PackageVersion Include="Annium.Logging.Console" Version="1.1.47" />
    <PackageVersion Include="Annium.Logging.Microsoft" Version="1.1.47" />
    <PackageVersion Include="Annium.Net.Http" Version="1.1.47" />
    <PackageVersion Include="Annium.Net.Servers.Web" Version="1.1.47" />
    <PackageVersion Include="Annium.NodaTime.Serialization.Json" Version="1.1.47" />
    <PackageVersion Include="Annium.Serialization.Json" Version="1.1.47" />
    <PackageVersion Include="Annium.Serialization.Yaml" Version="1.1.47" />
    <PackageVersion Include="Annium.Testing" Version="1.1.47" />
    <PackageVersion Include="Annium.linq2db.PostgreSql" Version="1.1.35" />
    <PackageVersion Include="coverlet.collector" Version="10.0.1" />
    <PackageVersion Include="dbup-postgresql" Version="7.0.1" />
    <PackageVersion Include="Humanizer" Version="3.0.10" />
    <PackageVersion Include="LibGit2Sharp" Version="0.32.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="10.0.11" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="8.0.0" />
    <PackageVersion Include="Microsoft.VisualStudio.Threading.Analyzers" Version="17.14.15" />
    <PackageVersion Include="NodaTime.Serialization.JsonNet" Version="3.3.0" />
    <PackageVersion Include="NuGet.Packaging" Version="7.9.0" />
    <PackageVersion Include="NSwag.AspNetCore" Version="14.7.1" />
    <PackageVersion Include="QuikGraph.Graphviz" Version="2.5.0" />
    <PackageVersion Include="Scriban" Version="7.2.6" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    <PackageVersion Include="Testcontainers.PostgreSql" Version="4.14.0" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="4.0.0" />
    <PackageVersion Include="xunit.v3" Version="4.0.0" />
  </ItemGroup>
</Project>
