x-base: &base
  restart: always
  logging:
    driver: json-file
    options:
      max-size: 1m
      max-file: '1'
services:
  server:
    <<: *base
    build:
      context: .
      dockerfile: server/src/Annium.Xs.Server.Host/app.dockerfile
    image: xs_server
    container_name: xs_server
    volumes:
      - './run/server/configuration:/app/configuration'
      - './run/server/data:/app/data'
  db:
    <<: *base
    image: registry.annium.com/postgres:17-alpine
    container_name: xs_db
    ports:
      - '9991:5432'
    volumes:
      - 'db:/var/lib/postgresql/data'
    env_file: ./run/db/db.env
  site:
    <<: *base
    build:
      context: .
      dockerfile: site/app.dockerfile
    image: xs_site
    container_name: xs_site
    ports:
      - '9900:80'
volumes:
  db:
