version: '3.8'
x-base: &base
  restart: always
  logging:
    driver: json-file
    options:
      max-size: 1m
      max-file: '1'
services:
  server:
    <<: *base
    build:
      context: .
      dockerfile: server/src/Server.Host/app.dockerfile
    image: xs_server
    container_name: xs_server
    volumes:
      - './run/server/configuration:/app/configuration'
      - './run/server/data:/app/data'
  db:
    <<: *base
    image: registry.annium.com/postgres:15
    container_name: xs_db
    ports:
      - '9991:5432'
    volumes:
      - 'db:/var/lib/postgresql/data'
    env_file: ./run/db/db.env
  proxy:
    <<: *base
    image: nginx:alpine
    container_name: xs_proxy
    ports:
      - '9901:9901'
      - '9902:9902'
      - '9903:9903'
    volumes:
      - ./cfg/docker/nginx:/etc/nginx/conf.d/parts:ro
      - ./cfg/docker/proxy.conf:/etc/nginx/conf.d/default.conf:ro
  site:
    <<: *base
    build:
      context: .
      dockerfile: site/app.dockerfile
    image: xs_site
    container_name: xs_site
    ports:
      - '9900:80'
volumes:
  db:
