<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netcoreapp2.2</TargetFramework>
        <DebugType>Portable</DebugType>
        <OutputType>Library</OutputType>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../Xs.Registry.Shared.Client/Xs.Registry.Shared.Client.csproj" />
    </ItemGroup>
</Project>