<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageId>Xs.Core</PackageId>
        <PackageVersion>0.1.0</PackageVersion>
        <Description>XS core project. Intended to be a bridge between cli and registry stuff. Obsolete.</Description>
        <TargetFramework>netcoreapp2.2</TargetFramework>
        <OutputType>Library</OutputType>
        <DebugType>Portable</DebugType>
    </PropertyGroup>
</Project>