<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageId>Server.Abstractions</PackageId>
        <PackageVersion>0.1.0</PackageVersion>
        <Description>XS registry abstract server project. Contains all stuff, shared between project servers. Is not intended to be used in main server.</Description>
        <TargetFramework>net7.0</TargetFramework>
        <OutputType>Library</OutputType>
        <DebugType>portable</DebugType>
        <LangVersion>11.0</LangVersion>
        <WarningsAsErrors>true</WarningsAsErrors>
        <IsPackable>false</IsPackable>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../Server.DbOld/Server.DbOld.csproj" />
        <ProjectReference Include="../Server.Shared/Server.Shared.csproj" />
    </ItemGroup>
</Project>