<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Solutions>Xx</Solutions>
        <OutputType>Library</OutputType>
        <IsPackable>false</IsPackable>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../Xx.Cli.Core/Xx.Cli.Core.csproj" />
    </ItemGroup>
    <ItemGroup>
        <EmbeddedResource Include="Templates/**" />
        <EmbeddedResource Remove="Templates/.*" />
    </ItemGroup>
</Project>