<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <PackageId>Xs.Registry.Main</PackageId>
        <PackageVersion>0.1.0</PackageVersion>
        <Description>XS registry main server. Generic management and project-independent endpoints.</Description>
        <TargetFramework>net5.0</TargetFramework>
        <OutputType>Exe</OutputType>
        <DebugType>portable</DebugType>
        <LangVersion>9.0</LangVersion>
        <WarningsAsErrors>true</WarningsAsErrors>
        <IsPackable>false</IsPackable>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../Xs.Registry.Db/Xs.Registry.Db.csproj" />
        <ProjectReference Include="../Xs.Registry.Shared/Xs.Registry.Shared.csproj" />
    </ItemGroup>
</Project>