<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Solutions>Xx</Solutions>
        <OutputType>Library</OutputType>
        <IsPackable>false</IsPackable>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Annium.Net.Http" />
    </ItemGroup>
</Project>