<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageId>Server.Client</PackageId>
        <PackageVersion>0.1.0</PackageVersion>
        <Description>XS registry client for main server.</Description>
        <Solutions>Xs</Solutions>
        <TargetFramework>net8.0</TargetFramework>
        <OutputType>Library</OutputType>
        <DebugType>portable</DebugType>
        <WarningsAsErrors>true</WarningsAsErrors>
        <IsPackable>false</IsPackable>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Annium.Net.Http" Version="0.1.0" />
    </ItemGroup>
</Project>