<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Solutions>Annium.Xs</Solutions>
    <OutputType>Library</OutputType>
    <IsPackable>false</IsPackable>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Annium.Xs.Server.Abstractions/Annium.Xs.Server.Abstractions.csproj" />
  </ItemGroup>
  <ItemGroup>
      <PackageReference Include="Annium.DbUp.PostgreSql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Scripts/**/*.sql" />
  </ItemGroup>
</Project>
