<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netcoreapp2.2</TargetFramework>
        <DebugType>Portable</DebugType>
        <OutputType>Library</OutputType>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Annium.Extensions.DependencyInjection" Version="0.1.0" />
        <PackageReference Include="Annium.Extensions.Net.Http" Version="0.1.0" />
    </ItemGroup>
</Project>