<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageId>Server.Domain</PackageId>
        <PackageVersion>0.1.0</PackageVersion>
        <Description>Server.Domain</Description>
        <TargetFramework>net7.0</TargetFramework>
        <OutputType>Library</OutputType>
        <DebugType>portable</DebugType>
        <LangVersion>11.0</LangVersion>
        <WarningsAsErrors>true</WarningsAsErrors>
        <IsPackable>false</IsPackable>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../../../../backend/base/Core/src/Annium.Core.Mapper/Annium.Core.Mapper.csproj" />
        <ProjectReference Include="../../../../backend/base/Data/src/Annium.Data.Models/Annium.Data.Models.csproj" />
    </ItemGroup>
</Project>