version: "3.4"
services:
  db_tool:
    image: "mongo-express:latest"
    container_name: registry_db_tool
    restart: always
    environment:
      - "ME_CONFIG_MONGODB_SERVER=db"
    ports:
      - "9912:8081"
    env_file: ../run/db_tool.env
networks:
  default:
    external:
      name: registry
