version: "3.4"
services:
  dotnet:
    build:
      context: ../src
      dockerfile: Xs.Registry.Dotnet/Dockerfile
    image: registry_dotnet
    container_name: registry_dotnet
    restart: always
    ports:
      - "9902:9902"
    volumes:
      - "../run:/app/data"
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: "1"
networks:
  default:
    external:
      name: registry
