version: "3.4"
services:
  site:
    build:
      context: ../site/src
      dockerfile: site/Dockerfile
    image: registry_site
    container_name: registry_site
    restart: always
    ports:
      - "9900:80"
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: "1"
networks:
  default:
    external:
      name: registry
