<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Solutions>Xx</Solutions>
        <OutputType>Library</OutputType>
        <IsPackable>false</IsPackable>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../Server.Abstractions/Server.Abstractions.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="NuGet.Packaging" />
    </ItemGroup>
    <ItemGroup>
        <EmbeddedResource Include="Scripts/**/*.sql" />
    </ItemGroup>
</Project>