<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageId>Xs.RegistryClient.Server</PackageId>
        <PackageVersion>0.1.0</PackageVersion>
        <Description>XS registry client for project server.</Description>
        <TargetFramework>netcoreapp2.2</TargetFramework>
        <OutputType>Library</OutputType>
        <DebugType>Portable</DebugType>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../Xs.RegistryClient.Shared/Xs.RegistryClient.Shared.csproj" />
    </ItemGroup>
</Project>