<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netcoreapp2.2</TargetFramework>
        <DebugType>Portable</DebugType>
        <OutputType>Exe</OutputType>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../Xs.Execution/Xs.Execution.csproj" />
        <ProjectReference Include="../Xs.Registry.Abstract/Xs.Registry.Abstract.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="NuGet.Packaging" Version="4.9.3" />
    </ItemGroup>
</Project>