<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Solutions>Xx</Solutions>
        <OutputType>Library</OutputType>
        <IsPackable>false</IsPackable>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Annium.Configuration.CommandLine" />
        <PackageReference Include="Annium.Configuration.Yaml" />
        <PackageReference Include="Annium.Data.Operations.Serialization.Json" />
        <PackageReference Include="Annium.Extensions.Arguments" />
        <PackageReference Include="Annium.Extensions.CommandLine" />
        <PackageReference Include="Annium.Extensions.Shell" />
        <PackageReference Include="Annium.Logging.Console" />
        <PackageReference Include="Annium.Net.Http" />
        <PackageReference Include="Annium.NodaTime.Serialization.Json" />
        <PackageReference Include="Annium.Serialization.Json" />
        <PackageReference Include="Annium.Serialization.Yaml" />
        <PackageReference Include="Scriban" />
    </ItemGroup>
</Project>