<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageId>Xs.Cli.Dotnet</PackageId>
        <PackageVersion>0.1.0</PackageVersion>
        <Description>XS cli .NET project. All staff for .NET related things: project parsing, building, publishing, etc.</Description>
        <TargetFramework>netcoreapp2.2</TargetFramework>
        <OutputType>library</OutputType>
        <DebugType>portable</DebugType>
        <WarningsAsErrors>true</WarningsAsErrors>
    </PropertyGroup>
    <ItemGroup>
        <EmbeddedResource Include="Templates/**" />
        <EmbeddedResource Remove="Templates/.*" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="../Xs.Cli.Core/Xs.Cli.Core.csproj" />
    </ItemGroup>
</Project>