<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageId>Xs.Cli.Dotnet</PackageId>
        <PackageVersion>0.1.0</PackageVersion>
        <Description>XS cli .NET project. All staff for .NET related things: project parsing, building, publishing, etc.</Description>
        <Solutions>Xs</Solutions>
        <TargetFramework>net8.0</TargetFramework>
        <OutputType>Library</OutputType>
        <DebugType>portable</DebugType>
        <WarningsAsErrors>true</WarningsAsErrors>
        <IsPackable>false</IsPackable>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../Xs.Cli.Core/Xs.Cli.Core.csproj" />
    </ItemGroup>
    <ItemGroup>
        <EmbeddedResource Include="Templates/**" />
        <EmbeddedResource Remove="Templates/.*" />
    </ItemGroup>
    <ItemGroup>
        <Content Include="Templates\WebAssemblyApplication\Pages\Home\HomePage.razor_tpl" />
    </ItemGroup>
</Project>