<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageId>Server.IntegrationTestsBase</PackageId>
        <PackageVersion>0.1.0</PackageVersion>
        <Description>Xs.Registry.Tests</Description>
        <TargetFramework>net7.0</TargetFramework>
        <OutputType>Library</OutputType>
        <DebugType>portable</DebugType>
        <LangVersion>11.0</LangVersion>
        <WarningsAsErrors>true</WarningsAsErrors>
        <IsPackable>false</IsPackable>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../../../../backend/third-party/AspNetCore/src/Annium.AspNetCore.IntegrationTesting/Annium.AspNetCore.IntegrationTesting.csproj" />
    </ItemGroup>
</Project>