<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <Solutions>Xx</Solutions>
        <OutputType>Exe</OutputType>
        <IsPackable>false</IsPackable>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../Server.Dotnet/Server.Dotnet.csproj" />
        <ProjectReference Include="../Server.Main/Server.Main.csproj" />
        <ProjectReference Include="../Server.Node/Server.Node.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Swashbuckle.AspNetCore" />
    </ItemGroup>
</Project>