<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <PackageId>Server.Host</PackageId>
        <PackageVersion>0.1.0</PackageVersion>
        <Description>XS registry main server. Generic management and project-independent endpoints.</Description>
        <TargetFramework>net7.0</TargetFramework>
        <OutputType>Exe</OutputType>
        <DebugType>portable</DebugType>
        <LangVersion>11.0</LangVersion>
        <WarningsAsErrors>true</WarningsAsErrors>
        <IsPackable>false</IsPackable>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../Server.Db/Server.Db.csproj" />
        <ProjectReference Include="../Server.Shared/Server.Shared.csproj" />
    </ItemGroup>
</Project>