<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageId>Xs.Cli.Core</PackageId>
        <PackageVersion>0.1.0</PackageVersion>
        <Description>XS cli core project. Provides access to base models, tools, projects, etc.</Description>
        <TargetFramework>net7.0</TargetFramework>
        <OutputType>Library</OutputType>
        <DebugType>portable</DebugType>
        <LangVersion>11.0</LangVersion>
        <WarningsAsErrors>true</WarningsAsErrors>
        <IsPackable>false</IsPackable>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../../../../backend/base/Configuration/src/Annium.Configuration.CommandLine/Annium.Configuration.CommandLine.csproj" />
        <ProjectReference Include="../../../../backend/base/Configuration/src/Annium.Configuration.Yaml/Annium.Configuration.Yaml.csproj" />
        <ProjectReference Include="../../../../backend/base/Extensions/src/Annium.Extensions.Arguments/Annium.Extensions.Arguments.csproj" />
        <ProjectReference Include="../../../../backend/base/Extensions/src/Annium.Extensions.CommandLine/Annium.Extensions.CommandLine.csproj" />
        <ProjectReference Include="../../../../backend/base/Extensions/src/Annium.Extensions.Shell/Annium.Extensions.Shell.csproj" />
        <ProjectReference Include="../../../../backend/base/Net/src/Annium.Net.Http/Annium.Net.Http.csproj" />
        <ProjectReference Include="../../../../backend/base/Serialization/src/Annium.Serialization.Json/Annium.Serialization.Json.csproj" />
        <ProjectReference Include="../../../../backend/base/Serialization/src/Annium.Serialization.Yaml/Annium.Serialization.Yaml.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Scriban" Version="5.5.1" />
    </ItemGroup>
</Project>