<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageId>Server.Node</PackageId>
        <PackageVersion>0.1.0</PackageVersion>
        <Description>XS registry Node.JS project. Handles interaction with npm/yarn.</Description>
        <TargetFramework>net7.0</TargetFramework>
        <OutputType>Library</OutputType>
        <DebugType>portable</DebugType>
        <LangVersion>11.0</LangVersion>
        <WarningsAsErrors>true</WarningsAsErrors>
        <IsPackable>false</IsPackable>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../Server.Abstractions/Server.Abstractions.csproj" />
    </ItemGroup>
</Project>