<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageId>Server.Db</PackageId>
        <PackageVersion>0.1.0</PackageVersion>
        <Description>Server.Db</Description>
        <TargetFramework>net7.0</TargetFramework>
        <OutputType>Library</OutputType>
        <DebugType>portable</DebugType>
        <LangVersion>11.0</LangVersion>
        <WarningsAsErrors>true</WarningsAsErrors>
        <IsPackable>false</IsPackable>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../../../../backend/base/Configuration/src/Annium.Configuration.Yaml/Annium.Configuration.Yaml.csproj" />
        <ProjectReference Include="../../../../backend/third-party/linq2db/src/Annium.linq2db.PostgreSql/Annium.linq2db.PostgreSql.csproj" />
        <ProjectReference Include="../Server.Domain/Server.Domain.csproj" />
        <ProjectReference Include="../../../../tools/xdb/src/Xdb.Core/Xdb.Core.csproj" />
    </ItemGroup>
</Project>