<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <PackageId>Xs.Registry.Dotnet</PackageId>
        <PackageVersion>0.1.0</PackageVersion>
        <Description>XS registry .NET project. Handles interaction with NuGet.</Description>
        <TargetFramework>net5.0</TargetFramework>
        <OutputType>Exe</OutputType>
        <DebugType>portable</DebugType>
        <LangVersion>preview</LangVersion>
        <WarningsAsErrors>true</WarningsAsErrors>
        <IsPackable>false</IsPackable>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../Xs.Registry.Abstract/Xs.Registry.Abstract.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="NuGet.Packaging" Version="5.8.0" />
    </ItemGroup>
</Project>