<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Solutions>Xx</Solutions>
        <OutputType>Library</OutputType>
        <IsPackable>false</IsPackable>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Annium.AspNetCore.Extensions" />
        <PackageReference Include="Annium.Configuration.Yaml" />
        <PackageReference Include="Annium.Infrastructure.Hosting" />
        <PackageReference Include="Annium.linq2db.PostgreSql" />
        <PackageReference Include="Annium.Logging.Console" />
        <PackageReference Include="Annium.Logging.Microsoft" />
        <PackageReference Include="Annium.Net.Http" />
        <PackageReference Include="dbup-postgresql" />
        <PackageReference Include="Microsoft.Extensions.Logging.Console" />
        <PackageReference Include="NodaTime.Serialization.JsonNet" />
        <PackageReference Include="NSwag.AspNetCore" />
    </ItemGroup>
    <ItemGroup>
        <EmbeddedResource Include="Scripts/**/*.sql" />
    </ItemGroup>
</Project>