<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageId>Server.Node.Tests</PackageId>
        <PackageVersion>0.1.0</PackageVersion>
        <Description>Xs.Registry.Node.Tests</Description>
        <TargetFramework>net7.0</TargetFramework>
        <OutputType>Exe</OutputType>
        <DebugType>portable</DebugType>
        <LangVersion>11.0</LangVersion>
        <WarningsAsErrors>true</WarningsAsErrors>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../../../../backend/base/Testing/src/Annium.Testing.Assertions/Annium.Testing.Assertions.csproj" />
        <ProjectReference Include="../../src/Server.Host/Server.Host.csproj" />
        <ProjectReference Include="../Server.IntegrationTestsBase/Server.IntegrationTestsBase.csproj" />
        <ProjectReference Include="../../src/Server.Node/Server.Node.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="coverlet.msbuild" Version="3.2.0" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="7.0.1" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.4.1" />
        <PackageReference Include="xunit" Version="2.4.2" />
        <PackageReference Include="xunit.runner.visualstudio" Version="2.4.5" />
    </ItemGroup>
</Project>