<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageId>Xs.Registry.Node.Tests</PackageId>
        <PackageVersion>0.1.0</PackageVersion>
        <Description>Xs.Registry.Node.Tests</Description>
        <TargetFramework>net5.0</TargetFramework>
        <OutputType>Exe</OutputType>
        <DebugType>portable</DebugType>
        <LangVersion>9.0</LangVersion>
        <WarningsAsErrors>true</WarningsAsErrors>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../../src/Xs.Registry.Main/Xs.Registry.Main.csproj" />
        <ProjectReference Include="../../src/Xs.Registry.Node/Xs.Registry.Node.csproj" />
        <ProjectReference Include="../Xs.Registry.Tests/Xs.Registry.Tests.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Annium.Testing.TestAdapter" Version="0.1.0" />
        <PackageReference Include="coverlet.msbuild" Version="3.0.2" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="5.0.3" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.8.3" />
    </ItemGroup>
</Project>