<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Solutions>Annium.Xs</Solutions>
    <OutputType>Library</OutputType>
    <IsPackable>false</IsPackable>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Annium.Xs.Cli.Core/Annium.Xs.Cli.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Humanizer" />
    <PackageReference Include="NuGet.Packaging" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Templates/**" />
    <EmbeddedResource Remove="Templates/.*" />
  </ItemGroup>
</Project>
