version: "3.4"
services:
  db:
    image: "postgres:10-alpine"
    container_name: registry_db
    restart: always
    ports:
      - "9911:5432"
    volumes:
      - "db:/var/lib/postgresql/data"
    env_file: ../run/db.env
networks:
  default:
    external:
      name: registry
volumes:
  db: