name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  actions: read

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    uses: annium/workflows/.github/workflows/dotnet-release.yml@v1
    secrets: inherit
